/* This file is generated by hayate-openapi. Do not edit it directly. */
import type { paths } from "./api-types.js";

export interface HayateClientOptions {
  baseUrl: string | URL;
  fetch?: typeof globalThis.fetch;
  headers?: HeadersInit | (() => HeadersInit | Promise<HeadersInit>);
  credentials?: RequestCredentials;
}

export type ClientRequestInit = Omit<RequestInit, "body" | "headers" | "method"> & {
  headers?: HeadersInit;
};

type Defined<T> = Exclude<T, undefined>;
type OperationParameters<Operation> = Operation extends { parameters: infer Parameters }
  ? {
      [Location in keyof Parameters as [Defined<Parameters[Location]>] extends [never]
        ? never
        : Location]: Defined<Parameters[Location]>;
    }
  : Record<never, never>;
type RequestBody<Operation, MediaType extends string> =
  Operation extends { requestBody?: infer Body }
    ? [Defined<Body>] extends [never]
      ? never
      : Defined<Body> extends { content: infer Content }
        ? MediaType extends keyof Content
          ? Content[MediaType]
          : never
        : never
    : never;
type Responses<Operation> = Operation extends { responses: infer Value } ? Value : never;
type JsonBody<ResponseValue> =
  ResponseValue extends { content: infer Content }
    ? Content extends Record<PropertyKey, unknown>
      ? Content[keyof Content]
      : never
    : never;
export type TypedResponse<Operation> = {
  [Status in Extract<keyof Responses<Operation>, number>]:
    Omit<globalThis.Response, "json" | "status"> & {
      readonly status: Status;
      json(): Promise<JsonBody<Responses<Operation>[Status]>>;
    };
}[Extract<keyof Responses<Operation>, number>];

type Operation0 = paths["/health"]["get"];
type Operation0Input = OperationParameters<Operation0>;
type Operation0Response = TypedResponse<Operation0>;

type Operation1 = paths["/canonicalize"]["get"];
type Operation1Input = OperationParameters<Operation1>;
type Operation1Response = TypedResponse<Operation1>;

type Operation2 = paths["/whoami"]["get"];
type Operation2Input = OperationParameters<Operation2>;
type Operation2Response = TypedResponse<Operation2>;

type Operation3 = paths["/todos"]["get"];
type Operation3Input = OperationParameters<Operation3>;
type Operation3Response = TypedResponse<Operation3>;

type Operation4 = paths["/todos"]["post"];
type Operation4Input = OperationParameters<Operation4> & { json: RequestBody<Operation4, "application/json"> };
type Operation4Response = TypedResponse<Operation4>;

type Operation5 = paths["/todos/{id}"]["get"];
type Operation5Input = OperationParameters<Operation5>;
type Operation5Response = TypedResponse<Operation5>;

type Operation6 = paths["/todos/{id}"]["delete"];
type Operation6Input = OperationParameters<Operation6>;
type Operation6Response = TypedResponse<Operation6>;

type Operation7 = paths["/uploads"]["post"];
type Operation7Input = OperationParameters<Operation7> & { form: Omit<RequestBody<Operation7, "multipart/form-data">, "file"> & { "file": Blob } };
type Operation7Response = TypedResponse<Operation7>;

type Operation8 = paths["/admin"]["get"];
type Operation8Input = OperationParameters<Operation8>;
type Operation8Response = TypedResponse<Operation8>;

type Operation9 = paths["/admin/{resource}"]["get"];
type Operation9Input = OperationParameters<Operation9>;
type Operation9Response = TypedResponse<Operation9>;

type Operation10 = paths["/admin/{resource}/create"]["get"];
type Operation10Input = OperationParameters<Operation10>;
type Operation10Response = TypedResponse<Operation10>;

type Operation11 = paths["/admin/{resource}/create"]["post"];
type Operation11Input = OperationParameters<Operation11>;
type Operation11Response = TypedResponse<Operation11>;

type Operation12 = paths["/admin/{resource}/bulk"]["post"];
type Operation12Input = OperationParameters<Operation12>;
type Operation12Response = TypedResponse<Operation12>;

type Operation13 = paths["/admin/{resource}/export.csv"]["get"];
type Operation13Input = OperationParameters<Operation13>;
type Operation13Response = TypedResponse<Operation13>;

type Operation14 = paths["/admin/{resource}/relationship/{field}/choices"]["get"];
type Operation14Input = OperationParameters<Operation14>;
type Operation14Response = TypedResponse<Operation14>;

type Operation15 = paths["/admin/{resource}/object/{object_id}"]["get"];
type Operation15Input = OperationParameters<Operation15>;
type Operation15Response = TypedResponse<Operation15>;

type Operation16 = paths["/admin/{resource}/object/{object_id}/edit"]["get"];
type Operation16Input = OperationParameters<Operation16>;
type Operation16Response = TypedResponse<Operation16>;

type Operation17 = paths["/admin/{resource}/object/{object_id}/edit"]["post"];
type Operation17Input = OperationParameters<Operation17>;
type Operation17Response = TypedResponse<Operation17>;

type Operation18 = paths["/admin/{resource}/object/{object_id}/history"]["get"];
type Operation18Input = OperationParameters<Operation18>;
type Operation18Response = TypedResponse<Operation18>;

type Operation19 = paths["/admin/{resource}/object/{object_id}/delete"]["get"];
type Operation19Input = OperationParameters<Operation19>;
type Operation19Response = TypedResponse<Operation19>;

type Operation20 = paths["/admin/{resource}/object/{object_id}/delete"]["post"];
type Operation20Input = OperationParameters<Operation20>;
type Operation20Response = TypedResponse<Operation20>;

type Operation21 = paths["/admin/{resource}/object/{object_id}/inline/{inline}"]["get"];
type Operation21Input = OperationParameters<Operation21>;
type Operation21Response = TypedResponse<Operation21>;

type Operation22 = paths["/admin/{resource}/object/{object_id}/inline/{inline}"]["post"];
type Operation22Input = OperationParameters<Operation22>;
type Operation22Response = TypedResponse<Operation22>;

type Operation23 = paths["/mcp"]["get"];
type Operation23Input = OperationParameters<Operation23>;
type Operation23Response = TypedResponse<Operation23>;

type Operation24 = paths["/mcp"]["post"];
type Operation24Input = OperationParameters<Operation24>;
type Operation24Response = TypedResponse<Operation24>;

type Operation25 = paths["/mcp"]["delete"];
type Operation25Input = OperationParameters<Operation25>;
type Operation25Response = TypedResponse<Operation25>;

export interface HayateClient {
  "health"(input?: Operation0Input, init?: ClientRequestInit): Promise<Operation0Response>;
  "canonicalize"(input?: Operation1Input, init?: ClientRequestInit): Promise<Operation1Response>;
  "whoami"(input?: Operation2Input, init?: ClientRequestInit): Promise<Operation2Response>;
  "listTodos"(input?: Operation3Input, init?: ClientRequestInit): Promise<Operation3Response>;
  "createTodo"(input: Operation4Input, init?: ClientRequestInit): Promise<Operation4Response>;
  "getTodo"(input: Operation5Input, init?: ClientRequestInit): Promise<Operation5Response>;
  "deleteTodo"(input: Operation6Input, init?: ClientRequestInit): Promise<Operation6Response>;
  "digestUpload"(input: Operation7Input, init?: ClientRequestInit): Promise<Operation7Response>;
  "get_admin"(input?: Operation8Input, init?: ClientRequestInit): Promise<Operation8Response>;
  "get_admin_resource"(input: Operation9Input, init?: ClientRequestInit): Promise<Operation9Response>;
  "get_admin_resource_create"(input: Operation10Input, init?: ClientRequestInit): Promise<Operation10Response>;
  "post_admin_resource_create"(input: Operation11Input, init?: ClientRequestInit): Promise<Operation11Response>;
  "post_admin_resource_bulk"(input: Operation12Input, init?: ClientRequestInit): Promise<Operation12Response>;
  "get_admin_resource_export_csv"(input: Operation13Input, init?: ClientRequestInit): Promise<Operation13Response>;
  "get_admin_resource_relationship_field_choices"(input: Operation14Input, init?: ClientRequestInit): Promise<Operation14Response>;
  "get_admin_resource_object_object_id"(input: Operation15Input, init?: ClientRequestInit): Promise<Operation15Response>;
  "get_admin_resource_object_object_id_edit"(input: Operation16Input, init?: ClientRequestInit): Promise<Operation16Response>;
  "post_admin_resource_object_object_id_edit"(input: Operation17Input, init?: ClientRequestInit): Promise<Operation17Response>;
  "get_admin_resource_object_object_id_history"(input: Operation18Input, init?: ClientRequestInit): Promise<Operation18Response>;
  "get_admin_resource_object_object_id_delete"(input: Operation19Input, init?: ClientRequestInit): Promise<Operation19Response>;
  "post_admin_resource_object_object_id_delete"(input: Operation20Input, init?: ClientRequestInit): Promise<Operation20Response>;
  "get_admin_resource_object_object_id_inline_inline"(input: Operation21Input, init?: ClientRequestInit): Promise<Operation21Response>;
  "post_admin_resource_object_object_id_inline_inline"(input: Operation22Input, init?: ClientRequestInit): Promise<Operation22Response>;
  "get_mcp"(input?: Operation23Input, init?: ClientRequestInit): Promise<Operation23Response>;
  "post_mcp"(input?: Operation24Input, init?: ClientRequestInit): Promise<Operation24Response>;
  "delete_mcp"(input?: Operation25Input, init?: ClientRequestInit): Promise<Operation25Response>;
}

type InputRecord = {
  path?: Record<string, unknown>;
  query?: Record<string, unknown>;
  header?: Record<string, unknown>;
  cookie?: Record<string, unknown>;
};

function buildUrl(
  baseUrl: string | URL,
  path: string,
  query: Record<string, unknown> | undefined,
): URL {
  const base = baseUrl.toString();
  const normalizedBase = base.endsWith("/") ? base : `${base}/`;
  const relativePath = path.startsWith("/") ? path.slice(1) : path;
  const url = new URL(relativePath, normalizedBase);
  if (query !== undefined) {
    url.search = encodeSearchValues(query).toString();
  }
  return url;
}

function encodePath(path: string, parameters: Record<string, unknown> | undefined): string {
  if (parameters !== undefined) {
    for (const [name, value] of Object.entries(parameters)) {
      if (value === undefined) {
        continue;
      }
      const encoded = Array.isArray(value)
        ? value.map((item) => encodeURIComponent(String(item))).join(",")
        : encodeURIComponent(String(value));
      path = path.replaceAll(`{${name}}`, encoded);
    }
  }
  if (/\{[^}]+\}/u.test(path)) {
    throw new TypeError(`Hayate client is missing a path parameter for ${path}`);
  }
  return path;
}

function appendSearchValue(search: URLSearchParams, name: string, value: unknown): void {
  if (value === undefined) {
    return;
  }
  if (Array.isArray(value)) {
    for (const item of value) {
      appendSearchValue(search, name, item);
    }
    return;
  }
  search.append(name, String(value));
}

function encodeSearchValues(values: unknown): URLSearchParams {
  const search = new URLSearchParams();
  if (typeof values !== "object" || values === null || Array.isArray(values)) {
    throw new TypeError("Hayate form and query inputs must be objects");
  }
  for (const [name, value] of Object.entries(values)) {
    appendSearchValue(search, name, value);
  }
  return search;
}

async function buildHeaders(
  options: HayateClientOptions,
  input: InputRecord,
  init: ClientRequestInit,
): Promise<Headers> {
  const configured =
    typeof options.headers === "function" ? await options.headers() : options.headers;
  const headers = new Headers(configured);
  for (const [name, value] of Object.entries(input.header ?? {})) {
    if (value !== undefined) {
      headers.set(name, Array.isArray(value) ? value.join(",") : String(value));
    }
  }
  const cookies: string[] = [];
  for (const [name, value] of Object.entries(input.cookie ?? {})) {
    const values = Array.isArray(value) ? value : [value];
    for (const item of values) {
      if (item !== undefined) {
        cookies.push(`${encodeURIComponent(name)}=${encodeURIComponent(String(item))}`);
      }
    }
  }
  if (cookies.length > 0) {
    const existing = headers.get("cookie");
    headers.set("cookie", [existing, ...cookies].filter(Boolean).join("; "));
  }
  new Headers(init.headers).forEach((value, name) => headers.set(name, value));
  return headers;
}

function setContentType(headers: Headers, mediaType: string): void {
  if (!headers.has("content-type")) {
    headers.set("content-type", mediaType);
  }
}

function appendFormValue(form: FormData, name: string, value: unknown): void {
  if (value === undefined) {
    return;
  }
  if (Array.isArray(value)) {
    for (const item of value) {
      appendFormValue(form, name, item);
    }
    return;
  }
  if (typeof Blob !== "undefined" && value instanceof Blob) {
    form.append(name, value);
    return;
  }
  form.append(name, String(value));
}

function encodeMultipart(values: unknown): FormData {
  if (typeof values !== "object" || values === null || Array.isArray(values)) {
    throw new TypeError("Hayate multipart input must be an object");
  }
  const form = new FormData();
  for (const [name, value] of Object.entries(values)) {
    appendFormValue(form, name, value);
  }
  return form;
}

export function createHayateClient(options: HayateClientOptions): HayateClient {
  const fetchImpl = options.fetch ?? globalThis.fetch;
  if (typeof fetchImpl !== "function") {
    throw new TypeError("Hayate client requires a Fetch implementation");
  }
  return {
    ["health"]: async (
      input: Operation0Input = {} as Operation0Input,
      init: ClientRequestInit = {},
    ): Promise<Operation0Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/health";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation0Response;
    },
    ["canonicalize"]: async (
      input: Operation1Input = {} as Operation1Input,
      init: ClientRequestInit = {},
    ): Promise<Operation1Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/canonicalize";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation1Response;
    },
    ["whoami"]: async (
      input: Operation2Input = {} as Operation2Input,
      init: ClientRequestInit = {},
    ): Promise<Operation2Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/whoami";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation2Response;
    },
    ["listTodos"]: async (
      input: Operation3Input = {} as Operation3Input,
      init: ClientRequestInit = {},
    ): Promise<Operation3Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/todos";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation3Response;
    },
    ["createTodo"]: async (
      input: Operation4Input,
      init: ClientRequestInit = {},
    ): Promise<Operation4Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/todos";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const bodyValue = input.json;
      let body: BodyInit | undefined;
      if (bodyValue !== undefined) {
        body = JSON.stringify(bodyValue);
        setContentType(headers, "application/json");
      }
      const request: RequestInit = {
        ...init,
        method: "POST",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation4Response;
    },
    ["getTodo"]: async (
      input: Operation5Input,
      init: ClientRequestInit = {},
    ): Promise<Operation5Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/todos/{id}";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation5Response;
    },
    ["deleteTodo"]: async (
      input: Operation6Input,
      init: ClientRequestInit = {},
    ): Promise<Operation6Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/todos/{id}";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "DELETE",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation6Response;
    },
    ["digestUpload"]: async (
      input: Operation7Input,
      init: ClientRequestInit = {},
    ): Promise<Operation7Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/uploads";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const bodyValue = input.form;
      let body: BodyInit | undefined;
      if (bodyValue !== undefined) {
        body = encodeMultipart(bodyValue);
      }
      const request: RequestInit = {
        ...init,
        method: "POST",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation7Response;
    },
    ["get_admin"]: async (
      input: Operation8Input = {} as Operation8Input,
      init: ClientRequestInit = {},
    ): Promise<Operation8Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/admin";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation8Response;
    },
    ["get_admin_resource"]: async (
      input: Operation9Input,
      init: ClientRequestInit = {},
    ): Promise<Operation9Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/admin/{resource}";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation9Response;
    },
    ["get_admin_resource_create"]: async (
      input: Operation10Input,
      init: ClientRequestInit = {},
    ): Promise<Operation10Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/admin/{resource}/create";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation10Response;
    },
    ["post_admin_resource_create"]: async (
      input: Operation11Input,
      init: ClientRequestInit = {},
    ): Promise<Operation11Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/admin/{resource}/create";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "POST",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation11Response;
    },
    ["post_admin_resource_bulk"]: async (
      input: Operation12Input,
      init: ClientRequestInit = {},
    ): Promise<Operation12Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/admin/{resource}/bulk";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "POST",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation12Response;
    },
    ["get_admin_resource_export_csv"]: async (
      input: Operation13Input,
      init: ClientRequestInit = {},
    ): Promise<Operation13Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/admin/{resource}/export.csv";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation13Response;
    },
    ["get_admin_resource_relationship_field_choices"]: async (
      input: Operation14Input,
      init: ClientRequestInit = {},
    ): Promise<Operation14Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/admin/{resource}/relationship/{field}/choices";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation14Response;
    },
    ["get_admin_resource_object_object_id"]: async (
      input: Operation15Input,
      init: ClientRequestInit = {},
    ): Promise<Operation15Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/admin/{resource}/object/{object_id}";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation15Response;
    },
    ["get_admin_resource_object_object_id_edit"]: async (
      input: Operation16Input,
      init: ClientRequestInit = {},
    ): Promise<Operation16Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/admin/{resource}/object/{object_id}/edit";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation16Response;
    },
    ["post_admin_resource_object_object_id_edit"]: async (
      input: Operation17Input,
      init: ClientRequestInit = {},
    ): Promise<Operation17Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/admin/{resource}/object/{object_id}/edit";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "POST",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation17Response;
    },
    ["get_admin_resource_object_object_id_history"]: async (
      input: Operation18Input,
      init: ClientRequestInit = {},
    ): Promise<Operation18Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/admin/{resource}/object/{object_id}/history";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation18Response;
    },
    ["get_admin_resource_object_object_id_delete"]: async (
      input: Operation19Input,
      init: ClientRequestInit = {},
    ): Promise<Operation19Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/admin/{resource}/object/{object_id}/delete";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation19Response;
    },
    ["post_admin_resource_object_object_id_delete"]: async (
      input: Operation20Input,
      init: ClientRequestInit = {},
    ): Promise<Operation20Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/admin/{resource}/object/{object_id}/delete";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "POST",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation20Response;
    },
    ["get_admin_resource_object_object_id_inline_inline"]: async (
      input: Operation21Input,
      init: ClientRequestInit = {},
    ): Promise<Operation21Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/admin/{resource}/object/{object_id}/inline/{inline}";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation21Response;
    },
    ["post_admin_resource_object_object_id_inline_inline"]: async (
      input: Operation22Input,
      init: ClientRequestInit = {},
    ): Promise<Operation22Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/admin/{resource}/object/{object_id}/inline/{inline}";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "POST",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation22Response;
    },
    ["get_mcp"]: async (
      input: Operation23Input = {} as Operation23Input,
      init: ClientRequestInit = {},
    ): Promise<Operation23Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/mcp";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "GET",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation23Response;
    },
    ["post_mcp"]: async (
      input: Operation24Input = {} as Operation24Input,
      init: ClientRequestInit = {},
    ): Promise<Operation24Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/mcp";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "POST",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation24Response;
    },
    ["delete_mcp"]: async (
      input: Operation25Input = {} as Operation25Input,
      init: ClientRequestInit = {},
    ): Promise<Operation25Response> => {
      const runtimeInput = input as unknown as InputRecord;
      let path = "/mcp";
      path = encodePath(path, runtimeInput.path);
      const url = buildUrl(options.baseUrl, path, runtimeInput.query);
      const headers = await buildHeaders(options, runtimeInput, init);
      const body: BodyInit | undefined = undefined;
      const request: RequestInit = {
        ...init,
        method: "DELETE",
        headers,
      };
      if (body !== undefined) request.body = body;
      if (
        request.credentials === undefined &&
        options.credentials !== undefined
      ) {
        request.credentials = options.credentials;
      }
      const response = await fetchImpl(url, request);
      return response as Operation25Response;
    },
  };
}
