schema = 1
hayate_admin_version = "0.1.0"
hayate_admin_commit = "eddd6213d1ebcd98d9b54a89fde883a349484ba0"
hayate_htmx_version = "0.2.0"
hayate_htmx_commit = "c133900998c487a44d40a103c52f2d469047deda"
vendored_paths = ["src/hayate_admin", "src/hayate_htmx"]
