"""Generate compatibility evidence from the checked lock and runtime manifests."""

from __future__ import annotations

import argparse
import hashlib
import json
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGES = (
    ("create-hayate", "Scaffold source"),
    ("hayate", "Application core and runtime adapters"),
    ("hayate-openapi", "OpenAPI 3.1 and Scalar"),
    ("hayate-mcp", "MCP transport and tools runtime"),
    ("hayate-sql", "Checked SQL and database adapters"),
    ("workers-py", "Cloudflare Python APIs"),
    ("workers-runtime-sdk", "Workers runtime packaging"),
)


def _load() -> dict[str, object]:
    lock_path = ROOT / "uv.lock"
    lock = tomllib.loads(lock_path.read_text(encoding="utf-8"))
    manifest = tomllib.loads((ROOT / "golden-app.toml").read_text(encoding="utf-8"))
    wrangler = tomllib.loads((ROOT / "wrangler.toml").read_text(encoding="utf-8"))
    locked = {
        package["name"]: package["version"]
        for package in lock["package"]
        if isinstance(package, dict) and "name" in package and "version" in package
    }
    generated_by = str(manifest["generated_by"])
    scaffold_name, scaffold_version = generated_by.rsplit(" ", 1)
    locked[scaffold_name] = scaffold_version
    rows = [{"package": name, "version": locked[name], "role": role} for name, role in PACKAGES]
    return {
        "schema_version": manifest["schema_version"],
        "generated_by": generated_by,
        "lock_sha256": hashlib.sha256(lock_path.read_bytes()).hexdigest(),
        "python": manifest["python_line"],
        "node": manifest["node_line"],
        "mcp_revision": manifest["mcp_revision"],
        "workers": {
            "compatibility_date": wrangler["compatibility_date"],
            "flags": wrangler["compatibility_flags"],
            "default_entrypoint": manifest["default_workers_entrypoint"],
            "global_entrypoint": manifest["global_workers_entrypoint"],
        },
        "packages": rows,
    }


def _markdown(data: dict[str, object]) -> str:
    workers = data["workers"]
    assert isinstance(workers, dict)
    packages = data["packages"]
    assert isinstance(packages, list)
    rows = "\n".join(
        f"| `{row['package']}` | `{row['version']}` | {row['role']} |"
        for row in packages
        if isinstance(row, dict)
    )
    flags = ", ".join(f"`{flag}`" for flag in workers["flags"])
    return f"""# Tested compatibility

This file is generated by `scripts/export_compatibility.py` from `uv.lock`,
`golden-app.toml`, and `wrangler.toml`. Do not edit it manually.

| Package | Locked version | Golden-path role |
|---|---:|---|
{rows}

## Runtime contract

| Boundary | Tested value |
|---|---|
| Python | `{data["python"]}` |
| Node.js | `{data["node"]}` |
| MCP revision | `{data["mcp_revision"]}` |
| Workers compatibility date | `{workers["compatibility_date"]}` |
| Workers flags | {flags} |
| Default entrypoint | {workers["default_entrypoint"]} |
| Optional global entrypoint | {workers["global_entrypoint"]} |

Lock SHA-256: `{data["lock_sha256"]}`
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = _load()
    outputs = {
        ROOT / "compatibility.json": json.dumps(data, indent=2, sort_keys=True) + "\n",
        ROOT / "COMPATIBILITY.md": _markdown(data),
    }
    if args.check:
        stale = [
            str(path.relative_to(ROOT))
            for path, expected in outputs.items()
            if not path.exists() or path.read_text(encoding="utf-8") != expected
        ]
        if stale:
            parser.error(f"generated compatibility evidence is stale: {', '.join(stale)}")
        return 0
    for path, content in outputs.items():
        path.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
