"""OpenAPI 3.1 and hardened Scalar registration."""

from hayate import Hayate
from hayate_openapi import OpenApi, cookie_security


def register(app: Hayate) -> None:
    OpenApi(
        app,
        title="golden-app",
        version="0.1.0",
        description="Generated by create-hayate from executable route contracts.",
        security_schemes={
            "CloudflareAccess": cookie_security(
                "CF_Authorization",
                description=(
                    "Cloudflare Access application token. Browser sessions send this "
                    "cookie through the Access proxy; service clients authenticate to "
                    "Access before the request reaches this application."
                ),
            )
        },
        security=[{"CloudflareAccess": []}],
    ).register(app)
