"""Generated by hayate-sql. Do not edit by hand."""

from typing import TypedDict, cast

from hayate_sql import (
    Cardinality,
    Column,
    CommandResult,
    Database,
    Parameter,
    Query,
)


class CountAdminAuditEventsRow(TypedDict):
    total: int


COUNT_ADMIN_AUDIT_EVENTS_QUERY = Query(
    name="count_admin_audit_events",
    sql=(
        "SELECT COUNT(*) AS total\n"
        "FROM admin_audit_events\n"
        "WHERE owner = ?1 AND resource = ?2 AND object_id = ?3"
    ),
    cardinality=Cardinality.ONE,
    parameters=(
        Parameter("owner", "str"),
        Parameter("resource", "str"),
        Parameter("object_id", "str"),
    ),
    columns=(Column("total", "int"),),
    timeout_ms=None,
)


async def count_admin_audit_events(
    db: Database,
    /,
    *,
    owner: str,
    resource: str,
    object_id: str,
) -> CountAdminAuditEventsRow:
    return cast(
        "CountAdminAuditEventsRow",
        await db.run(
            COUNT_ADMIN_AUDIT_EVENTS_QUERY,
            owner=owner,
            resource=resource,
            object_id=object_id,
        ),
    )


class CountAdminTodosRow(TypedDict):
    total: int


COUNT_ADMIN_TODOS_QUERY = Query(
    name="count_admin_todos",
    sql=(
        "SELECT COUNT(*) AS total\n"
        "FROM todos\n"
        "WHERE owner = ?1\n"
        "  AND (?2 = '' OR instr(lower(title), lower(?2)) > 0)"
    ),
    cardinality=Cardinality.ONE,
    parameters=(
        Parameter("owner", "str"),
        Parameter("search", "str"),
    ),
    columns=(Column("total", "int"),),
    timeout_ms=None,
)


async def count_admin_todos(
    db: Database,
    /,
    *,
    owner: str,
    search: str,
) -> CountAdminTodosRow:
    return cast(
        "CountAdminTodosRow",
        await db.run(
            COUNT_ADMIN_TODOS_QUERY,
            owner=owner,
            search=search,
        ),
    )


CREATE_ADMIN_AUDIT_EVENT_QUERY = Query(
    name="create_admin_audit_event",
    sql=(
        "INSERT INTO admin_audit_events (\n"
        "    owner,\n"
        "    occurred_at,\n"
        "    phase,\n"
        "    action,\n"
        "    operation,\n"
        "    resource,\n"
        "    object_id,\n"
        "    actor_id,\n"
        "    error_type\n"
        ")\n"
        "VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9)"
    ),
    cardinality=Cardinality.EXEC,
    parameters=(
        Parameter("owner", "str"),
        Parameter("occurred_at", "str"),
        Parameter("phase", "str"),
        Parameter("action", "str"),
        Parameter("operation", "str?"),
        Parameter("resource", "str"),
        Parameter("object_id", "str?"),
        Parameter("actor_id", "str?"),
        Parameter("error_type", "str?"),
    ),
    columns=(),
    timeout_ms=None,
)


async def create_admin_audit_event(
    db: Database,
    /,
    *,
    owner: str,
    occurred_at: str,
    phase: str,
    action: str,
    operation: str | None,
    resource: str,
    object_id: str | None,
    actor_id: str | None,
    error_type: str | None,
) -> CommandResult:
    return cast(
        "CommandResult",
        await db.run(
            CREATE_ADMIN_AUDIT_EVENT_QUERY,
            owner=owner,
            occurred_at=occurred_at,
            phase=phase,
            action=action,
            operation=operation,
            resource=resource,
            object_id=object_id,
            actor_id=actor_id,
            error_type=error_type,
        ),
    )


class CreateAdminTodoRow(TypedDict):
    id: str
    title: str
    done: int


CREATE_ADMIN_TODO_QUERY = Query(
    name="create_admin_todo",
    sql=(
        "INSERT INTO todos (id, owner, title, done)\n"
        "VALUES (?1, ?2, ?3, ?4)\n"
        "RETURNING id, title, done"
    ),
    cardinality=Cardinality.ONE,
    parameters=(
        Parameter("todo_id", "str"),
        Parameter("owner", "str"),
        Parameter("title", "str"),
        Parameter("done", "bool"),
    ),
    columns=(
        Column("id", "str"),
        Column("title", "str"),
        Column("done", "int"),
    ),
    timeout_ms=None,
)


async def create_admin_todo(
    db: Database,
    /,
    *,
    todo_id: str,
    owner: str,
    title: str,
    done: bool,
) -> CreateAdminTodoRow:
    return cast(
        "CreateAdminTodoRow",
        await db.run(
            CREATE_ADMIN_TODO_QUERY,
            todo_id=todo_id,
            owner=owner,
            title=title,
            done=done,
        ),
    )


CREATE_TODO_QUERY = Query(
    name="create_todo",
    sql=("INSERT INTO todos (id, owner, title, done)\nVALUES (?1, ?2, ?3, 0)"),
    cardinality=Cardinality.EXEC,
    parameters=(
        Parameter("todo_id", "str"),
        Parameter("owner", "str"),
        Parameter("title", "str"),
    ),
    columns=(),
    timeout_ms=None,
)


async def create_todo(
    db: Database,
    /,
    *,
    todo_id: str,
    owner: str,
    title: str,
) -> CommandResult:
    return cast(
        "CommandResult",
        await db.run(
            CREATE_TODO_QUERY,
            todo_id=todo_id,
            owner=owner,
            title=title,
        ),
    )


DELETE_TODO_QUERY = Query(
    name="delete_todo",
    sql=("DELETE FROM todos\nWHERE owner = ?1 AND id = ?2"),
    cardinality=Cardinality.EXEC,
    parameters=(
        Parameter("owner", "str"),
        Parameter("todo_id", "str"),
    ),
    columns=(),
    timeout_ms=None,
)


async def delete_todo(
    db: Database,
    /,
    *,
    owner: str,
    todo_id: str,
) -> CommandResult:
    return cast(
        "CommandResult",
        await db.run(
            DELETE_TODO_QUERY,
            owner=owner,
            todo_id=todo_id,
        ),
    )


class GetTodoRow(TypedDict):
    id: str
    title: str
    done: int


GET_TODO_QUERY = Query(
    name="get_todo",
    sql=("SELECT id, title, done\nFROM todos\nWHERE owner = ?1 AND id = ?2"),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(
        Parameter("owner", "str"),
        Parameter("todo_id", "str"),
    ),
    columns=(
        Column("id", "str"),
        Column("title", "str"),
        Column("done", "int"),
    ),
    timeout_ms=None,
)


async def get_todo(
    db: Database,
    /,
    *,
    owner: str,
    todo_id: str,
) -> GetTodoRow | None:
    return cast(
        "GetTodoRow | None",
        await db.run(
            GET_TODO_QUERY,
            owner=owner,
            todo_id=todo_id,
        ),
    )


class ListAdminAuditEventsRow(TypedDict):
    occurred_at: str
    phase: str
    action: str
    operation: str | None
    resource: str
    object_id: str | None
    actor_id: str | None
    error_type: str | None


LIST_ADMIN_AUDIT_EVENTS_QUERY = Query(
    name="list_admin_audit_events",
    sql=(
        "SELECT occurred_at, phase, action, operation, resource, object_id, actor_id, error_type\n"
        "FROM admin_audit_events\n"
        "WHERE owner = ?1 AND resource = ?2 AND object_id = ?3\n"
        "ORDER BY id DESC\n"
        "LIMIT ?4 OFFSET ?5"
    ),
    cardinality=Cardinality.MANY,
    parameters=(
        Parameter("owner", "str"),
        Parameter("resource", "str"),
        Parameter("object_id", "str"),
        Parameter("limit", "int"),
        Parameter("offset", "int"),
    ),
    columns=(
        Column("occurred_at", "str"),
        Column("phase", "str"),
        Column("action", "str"),
        Column("operation", "str?"),
        Column("resource", "str"),
        Column("object_id", "str?"),
        Column("actor_id", "str?"),
        Column("error_type", "str?"),
    ),
    timeout_ms=None,
)


async def list_admin_audit_events(
    db: Database,
    /,
    *,
    owner: str,
    resource: str,
    object_id: str,
    limit: int,
    offset: int,
) -> list[ListAdminAuditEventsRow]:
    return cast(
        "list[ListAdminAuditEventsRow]",
        await db.run(
            LIST_ADMIN_AUDIT_EVENTS_QUERY,
            owner=owner,
            resource=resource,
            object_id=object_id,
            limit=limit,
            offset=offset,
        ),
    )


class ListAdminTodosDefaultRow(TypedDict):
    id: str
    title: str
    done: int


LIST_ADMIN_TODOS_DEFAULT_QUERY = Query(
    name="list_admin_todos_default",
    sql=(
        "SELECT id, title, done\n"
        "FROM todos\n"
        "WHERE owner = ?1\n"
        "  AND (?2 = '' OR instr(lower(title), lower(?2)) > 0)\n"
        "ORDER BY rowid DESC\n"
        "LIMIT ?3 OFFSET ?4"
    ),
    cardinality=Cardinality.MANY,
    parameters=(
        Parameter("owner", "str"),
        Parameter("search", "str"),
        Parameter("limit", "int"),
        Parameter("offset", "int"),
    ),
    columns=(
        Column("id", "str"),
        Column("title", "str"),
        Column("done", "int"),
    ),
    timeout_ms=None,
)


async def list_admin_todos_default(
    db: Database,
    /,
    *,
    owner: str,
    search: str,
    limit: int,
    offset: int,
) -> list[ListAdminTodosDefaultRow]:
    return cast(
        "list[ListAdminTodosDefaultRow]",
        await db.run(
            LIST_ADMIN_TODOS_DEFAULT_QUERY,
            owner=owner,
            search=search,
            limit=limit,
            offset=offset,
        ),
    )


class ListAdminTodosTitleAscRow(TypedDict):
    id: str
    title: str
    done: int


LIST_ADMIN_TODOS_TITLE_ASC_QUERY = Query(
    name="list_admin_todos_title_asc",
    sql=(
        "SELECT id, title, done\n"
        "FROM todos\n"
        "WHERE owner = ?1\n"
        "  AND (?2 = '' OR instr(lower(title), lower(?2)) > 0)\n"
        "ORDER BY lower(title) ASC, id ASC\n"
        "LIMIT ?3 OFFSET ?4"
    ),
    cardinality=Cardinality.MANY,
    parameters=(
        Parameter("owner", "str"),
        Parameter("search", "str"),
        Parameter("limit", "int"),
        Parameter("offset", "int"),
    ),
    columns=(
        Column("id", "str"),
        Column("title", "str"),
        Column("done", "int"),
    ),
    timeout_ms=None,
)


async def list_admin_todos_title_asc(
    db: Database,
    /,
    *,
    owner: str,
    search: str,
    limit: int,
    offset: int,
) -> list[ListAdminTodosTitleAscRow]:
    return cast(
        "list[ListAdminTodosTitleAscRow]",
        await db.run(
            LIST_ADMIN_TODOS_TITLE_ASC_QUERY,
            owner=owner,
            search=search,
            limit=limit,
            offset=offset,
        ),
    )


class ListAdminTodosTitleDescRow(TypedDict):
    id: str
    title: str
    done: int


LIST_ADMIN_TODOS_TITLE_DESC_QUERY = Query(
    name="list_admin_todos_title_desc",
    sql=(
        "SELECT id, title, done\n"
        "FROM todos\n"
        "WHERE owner = ?1\n"
        "  AND (?2 = '' OR instr(lower(title), lower(?2)) > 0)\n"
        "ORDER BY lower(title) DESC, id DESC\n"
        "LIMIT ?3 OFFSET ?4"
    ),
    cardinality=Cardinality.MANY,
    parameters=(
        Parameter("owner", "str"),
        Parameter("search", "str"),
        Parameter("limit", "int"),
        Parameter("offset", "int"),
    ),
    columns=(
        Column("id", "str"),
        Column("title", "str"),
        Column("done", "int"),
    ),
    timeout_ms=None,
)


async def list_admin_todos_title_desc(
    db: Database,
    /,
    *,
    owner: str,
    search: str,
    limit: int,
    offset: int,
) -> list[ListAdminTodosTitleDescRow]:
    return cast(
        "list[ListAdminTodosTitleDescRow]",
        await db.run(
            LIST_ADMIN_TODOS_TITLE_DESC_QUERY,
            owner=owner,
            search=search,
            limit=limit,
            offset=offset,
        ),
    )


class ListTodosRow(TypedDict):
    id: str
    title: str
    done: int


LIST_TODOS_QUERY = Query(
    name="list_todos",
    sql=("SELECT id, title, done\nFROM todos\nWHERE owner = ?1\nORDER BY rowid ASC"),
    cardinality=Cardinality.MANY,
    parameters=(Parameter("owner", "str"),),
    columns=(
        Column("id", "str"),
        Column("title", "str"),
        Column("done", "int"),
    ),
    timeout_ms=None,
)


async def list_todos(
    db: Database,
    /,
    *,
    owner: str,
) -> list[ListTodosRow]:
    return cast(
        "list[ListTodosRow]",
        await db.run(
            LIST_TODOS_QUERY,
            owner=owner,
        ),
    )


class UpdateAdminTodoRow(TypedDict):
    id: str
    title: str
    done: int


UPDATE_ADMIN_TODO_QUERY = Query(
    name="update_admin_todo",
    sql=(
        "UPDATE todos\n"
        "SET title = ?3, done = ?4\n"
        "WHERE owner = ?1 AND id = ?2\n"
        "RETURNING id, title, done"
    ),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(
        Parameter("owner", "str"),
        Parameter("todo_id", "str"),
        Parameter("title", "str"),
        Parameter("done", "bool"),
    ),
    columns=(
        Column("id", "str"),
        Column("title", "str"),
        Column("done", "int"),
    ),
    timeout_ms=None,
)


async def update_admin_todo(
    db: Database,
    /,
    *,
    owner: str,
    todo_id: str,
    title: str,
    done: bool,
) -> UpdateAdminTodoRow | None:
    return cast(
        "UpdateAdminTodoRow | None",
        await db.run(
            UPDATE_ADMIN_TODO_QUERY,
            owner=owner,
            todo_id=todo_id,
            title=title,
            done=done,
        ),
    )


__all__ = [
    "COUNT_ADMIN_AUDIT_EVENTS_QUERY",
    "COUNT_ADMIN_TODOS_QUERY",
    "CREATE_ADMIN_AUDIT_EVENT_QUERY",
    "CREATE_ADMIN_TODO_QUERY",
    "CREATE_TODO_QUERY",
    "DELETE_TODO_QUERY",
    "GET_TODO_QUERY",
    "LIST_ADMIN_AUDIT_EVENTS_QUERY",
    "LIST_ADMIN_TODOS_DEFAULT_QUERY",
    "LIST_ADMIN_TODOS_TITLE_ASC_QUERY",
    "LIST_ADMIN_TODOS_TITLE_DESC_QUERY",
    "LIST_TODOS_QUERY",
    "UPDATE_ADMIN_TODO_QUERY",
    "CountAdminAuditEventsRow",
    "CountAdminTodosRow",
    "CreateAdminTodoRow",
    "GetTodoRow",
    "ListAdminAuditEventsRow",
    "ListAdminTodosDefaultRow",
    "ListAdminTodosTitleAscRow",
    "ListAdminTodosTitleDescRow",
    "ListTodosRow",
    "UpdateAdminTodoRow",
    "count_admin_audit_events",
    "count_admin_todos",
    "create_admin_audit_event",
    "create_admin_todo",
    "create_todo",
    "delete_todo",
    "get_todo",
    "list_admin_audit_events",
    "list_admin_todos_default",
    "list_admin_todos_title_asc",
    "list_admin_todos_title_desc",
    "list_todos",
    "update_admin_todo",
]
