"""Generated by hayate-sql. Do not edit by hand."""

from typing import TypedDict, cast

from hayate_sql import (
    Cardinality,
    Column,
    CommandResult,
    Database,
    Parameter,
    Query,
)

CREATE_TODO_QUERY = Query(
    name="create_todo",
    sql=("INSERT INTO todos (id, owner, title, done)\nVALUES (?1, ?2, ?3, 0)"),
    cardinality=Cardinality.EXEC,
    parameters=(
        Parameter("todo_id", "str"),
        Parameter("owner", "str"),
        Parameter("title", "str"),
    ),
    columns=(),
    timeout_ms=None,
)


async def create_todo(
    db: Database,
    /,
    *,
    todo_id: str,
    owner: str,
    title: str,
) -> CommandResult:
    return cast(
        "CommandResult",
        await db.run(
            CREATE_TODO_QUERY,
            todo_id=todo_id,
            owner=owner,
            title=title,
        ),
    )


DELETE_TODO_QUERY = Query(
    name="delete_todo",
    sql=("DELETE FROM todos\nWHERE owner = ?1 AND id = ?2"),
    cardinality=Cardinality.EXEC,
    parameters=(
        Parameter("owner", "str"),
        Parameter("todo_id", "str"),
    ),
    columns=(),
    timeout_ms=None,
)


async def delete_todo(
    db: Database,
    /,
    *,
    owner: str,
    todo_id: str,
) -> CommandResult:
    return cast(
        "CommandResult",
        await db.run(
            DELETE_TODO_QUERY,
            owner=owner,
            todo_id=todo_id,
        ),
    )


class GetTodoRow(TypedDict):
    id: str
    title: str
    done: int


GET_TODO_QUERY = Query(
    name="get_todo",
    sql=("SELECT id, title, done\nFROM todos\nWHERE owner = ?1 AND id = ?2"),
    cardinality=Cardinality.MAYBE_ONE,
    parameters=(
        Parameter("owner", "str"),
        Parameter("todo_id", "str"),
    ),
    columns=(
        Column("id", "str"),
        Column("title", "str"),
        Column("done", "int"),
    ),
    timeout_ms=None,
)


async def get_todo(
    db: Database,
    /,
    *,
    owner: str,
    todo_id: str,
) -> GetTodoRow | None:
    return cast(
        "GetTodoRow | None",
        await db.run(
            GET_TODO_QUERY,
            owner=owner,
            todo_id=todo_id,
        ),
    )


class ListTodosRow(TypedDict):
    id: str
    title: str
    done: int


LIST_TODOS_QUERY = Query(
    name="list_todos",
    sql=("SELECT id, title, done\nFROM todos\nWHERE owner = ?1\nORDER BY rowid ASC"),
    cardinality=Cardinality.MANY,
    parameters=(Parameter("owner", "str"),),
    columns=(
        Column("id", "str"),
        Column("title", "str"),
        Column("done", "int"),
    ),
    timeout_ms=None,
)


async def list_todos(
    db: Database,
    /,
    *,
    owner: str,
) -> list[ListTodosRow]:
    return cast(
        "list[ListTodosRow]",
        await db.run(
            LIST_TODOS_QUERY,
            owner=owner,
        ),
    )


__all__ = [
    "CREATE_TODO_QUERY",
    "DELETE_TODO_QUERY",
    "GET_TODO_QUERY",
    "LIST_TODOS_QUERY",
    "GetTodoRow",
    "ListTodosRow",
    "create_todo",
    "delete_todo",
    "get_todo",
    "list_todos",
]
